language: node_js
addons:
  apt:
    packages:
      - ldap-utils
      - slapd
jobs:
  include:
    - stage: test
      node_js:
        - 14.0.0
      before_script:
        - mkdir /tmp/slapd
        - 'slapd -f tests/fixtures/ldap/slapd.conf -h ldap://localhost:3389 &'
        - sleep 3
        - >-
          ldapadd -h localhost:3389 -D cn=Manager,dc=example,dc=com -w test -f
          tests/fixtures/ldap/base.ldif
      script:
        - npm run cover
        - npx codecov
        - cat ./build/coverage/lcov.info | npx coveralls
    - stage: doc
      node_js: lts/*
      skip_cleanup: 'true'
      script:
        - npm run lint
        - npm run docs
    - stage: release
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        script:
          - npx semantic-release
        cleanup: 'false'
branches:
  only:
    - master
    - /^greenkeeper/.*$/
    - /^mkpr/.*$/
    - /^npm-template-sync/.*$/
