language: node_js
node_js:
  - 10.16.3
  - 12.8.1
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache: npm
addons:
  apt:
    packages:
      - ldap-utils
      - slapd
before_script:
  - mkdir /tmp/slapd
  - 'slapd -f tests/fixtures/ldap/slapd.conf -h ldap://localhost:3389 &'
  - sleep 3
  - 'ldapadd -h localhost:3389 -D cn=Manager,dc=example,dc=com -w test -f tests/fixtures/ldap/base.ldif'
script:
  - npm run cover
  - npx codecov
  - cat ./build/coverage/lcov.info | npx coveralls
jobs:
  include:
    - stage: doc
      node_js: lts/*
      skip_cleanup: 'true'
      script:
        - npm run lint
        - npm run docs
    - stage: release
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        skip_cleanup: 'true'
        script:
          - npx semantic-release
