name: Extract openapi definition
'on': push
jobs:
  update_openapi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.15.4
      - run: npm install
      - run: node openapi/openapi.mjs
      - uses: gr2m/create-or-update-pull-request-action@v1.x
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: openapi/openapi.json
          title: update openapi definition
          branch: openapi
          commit-message: 'docs(openapi): update openapi definition'
